---
title: "Spatiotemporal models of species biomass split by maturity class"
author: "Philina English"
date: '2019-07-18'
output: html_document
params: 
    species: "Arrowtooth Flounder"

---

Choose one value for each parameter:

Species
```{r}
species <- params$species

# # Species run so far...
# species <- "Arrowtooth Flounder"
# species <- "Petrale Sole"
# species <- "English Sole"
# species <- "Dover Sole" # maturity data error for WCHG
# species <- "Southern Rock Sole"
# species <- "Flathead Sole"
 


# species <- "Silvergray Rockfish"
# species <- "Quillback Rockfish" # summer-birthing
species <- "Yelloweye Rockfish" # summer-birthing, overfished, 
# species <- "Bocaccio" # winter-birthing, overfished
# species <- "Sharpchin Rockfish"
# species <- "Splitnose Rockfish"

# species <- "Rougheye/Blackspotted Rockfish Complex"
# species <- "Redbanded Rockfish"
# species <- "Greenstriped Rockfish"
# # species <- "Copper Rockfish" # small sample
# species <- "Darkblotched Rockfish"
# # species <- "Shortbelly Rockfish" # small sample

# species <- "Pacific Ocean Perch" # schooling
# species <- "Widow Rockfish" # schooling
# species <- "Yellowtail Rockfish" # schooling
# species <- "Canary Rockfish" # schooling, winter-birthing
   
# species <- "Longspine Thornyhead"
# species <- "Shortspine Thornyhead"


# species <- "Walleye Pollock"
# species <- "Pacific Cod"
# species <- "Sablefish"
# species <- "Lingcod"
# species <- "Pacific Hake"
 
# species <- "North Pacific Spiny Dogfish" # note: using all data for maturity thresholds
# species <- "Longnose Skate"
# species <- "Big Skate"
# species <- "Spotted Ratfish"
# # species <- "Sandpaper Skate" # small sample
# # species <- "Brown Cat Shark" # small sample
```

Region 
```{r}
# region <- "All synoptic surveys"
 region <- "Both odd year surveys"
 # region <- "West Coast Vancouver Island"
 # region <- "West Coast Haida Gwaii"
```


Run all subsequent code...
```{r global_options, include=FALSE}
# covs <- gsub("\\+", "-", covariates)
spp <- gsub(" ", "-", gsub("\\/", "-", tolower(species)))

# folder to hold figs for this species
dir.create(file.path("figs", spp))
dir.create(file.path("data", spp))

knitr::opts_chunk$set(fig.width=11, fig.height=8.5, 
                      fig.path=paste0("figs/", spp, "/"),
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(gfplot)
library(gfdata)
library(sdmTMB)
library(gfranges)

fish <- readRDS(paste0("raw/bio-data-", spp, ""))

if (region == "Both odd year surveys") {
  survey <- c("SYN QCS", "SYN HS")
  model_ssid <- c(1, 3)
  ssid_string <- paste0(model_ssid, collapse = "n")
  years <- NULL
}

if (region == "West Coast Vancouver Island") {
  survey <- c("SYN WCVI")
  model_ssid <- c(4)
  ssid_string <- paste0(model_ssid, collapse = "n")
  years <- NULL
}

if (region == "West Coast Haida Gwaii") {
  survey <- c("SYN WCHG")
  model_ssid <- c(16)
  ssid_string <- paste0(model_ssid, collapse = "n")
  years <- NULL
}

if (region == "All synoptic surveys") {
  survey <- c("SYN QCS", "SYN HS", "SYN WCVI", "SYN WCHG")
  model_ssid <- c(1, 3, 4, 16)
  ssid_string <- paste0(model_ssid, collapse = "n")
  years <- NULL
}
```


# Split biomass by maturity

#### Calculate maturity weighted biomass if not done before
```{r}
 rm(biomass)
 rm(maturity)
# try(biomass <- readRDS(paste0("data/", spp, "/data-by-maturity-", spp, "-", ssid_string, ".rds")))

if (!exists("biomass")) {
  survey_sets <- readRDS(paste0("raw/event-data-", spp, ""))
  fish <- readRDS(paste0("raw/bio-data-", spp, ""))
  bath <- readRDS("data/bathymetry-data")
  # for POP: exclude sample with unusually large fish 
  # sizes are impossible given recorded catch weight
  # fish <- fish[fish$fishing_event_id!=1506954,]

 try({ 
   maturity <- split_catch_maturity(survey_sets, fish, bath,
    survey = survey,
    years = years,
    cutoff_quantile = c(.9995),
    plot = TRUE)
   })
  
  if(is.null(maturity$maturity)) {
  maturity <- split_catch_maturity(survey_sets, fish, bath,
    survey = c("SYN QCS","SYN HS","SYN WCVI","SYN WCHG"),
    years = years,
    cutoff_quantile = c(.9995),
    plot = TRUE
  )
  }
  maturity$data <- filter(maturity$data, ssid == model_ssid) 
  # %>% select(-adult_density, -imm_density) # if maturity model is deemed unuseful
  
  saveRDS(maturity$data, file = paste0("data/", spp, 
    "/data-by-maturity-", spp, "-", ssid_string, ".rds"
    ))
}
```

#### Save length~weight plots
```{r}
if (exists("maturity")) {
  print(maturity$mass_model)
  ggsave(
    file = paste0("figs/", spp, "/", spp, "-mass-model-", ssid_string, ".png"),
    dpi = 600,
    width = 8, 
    height = 10
  )
}
```

#### Save length at maturity plot 
```{r}
if (exists("maturity")) {
  png(
    file = paste0("figs/", spp, "/", spp, "-maturity-", ssid_string, ".png"), 
    res = 600,
    units = "in",
    width = 8, 
    height = 10
  )
  print(maturity$maturity)
  dev.off()
}

try(print(maturity$maturity))
```
