---
title: "Practice TMB"
output: html_notebook
---

```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("/Users/capitan/github/dfo/gfranges/")) 
library(sdmTMB)

```

Load data from cache

```{r}
d <- readRDS("data-cache/pacific-cod.rds")
d$density <- d$density_kgpm2
```



```{r}
# Gaussian:
pcod_gaus <- subset(d, density > 0 & year >= 2013)

pcod_spde_gaus <- make_spde(pcod_gaus$X, pcod_gaus$Y, n_knots = 50) #need to calculate X and Y (utms?)
m_pos <- sdmTMB(pcod_gaus,
  log(density) ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
  time = "year", spde = pcod_spde_gaus)

```




```{r}
d <- subset(pcod, year >= 2011) # subset for example speed
pcod_spde <- make_spde(d$X, d$Y, n_knots = 100) # only 100 knots for example speed
plot_spde(pcod_spde)

# Tweedie:
m <- sdmTMB(
  d, density ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
  time = "year", spde = pcod_spde, family = tweedie(link = "log"),
  silent = FALSE)

# Contents of the output object:
names(m)
m$model
TMB::sdreport(m$tmb_obj)
r <- m$tmb_obj$report()
names(r)

# Binomial:
pcod_binom <- d
pcod_binom$present <- ifelse(pcod_binom$density > 0, 1L, 0L)
m_bin <- sdmTMB(pcod_binom,
  present ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
  time = "year", spde = pcod_spde, family = binomial(link = "logit"))

# Gaussian:
pcod_gaus <- subset(d, density > 0 & year >= 2013)
pcod_spde_gaus <- make_spde(pcod_gaus$X, pcod_gaus$Y, n_knots = 50)
m_pos <- sdmTMB(pcod_gaus,
  log(density) ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
  time = "year", spde = pcod_spde_gaus)

## Not run: 
# Stan sampling (warning: slow going and priors are flat).

# Must load tmbstan first and then TMB and/or sdmTMB
# or you will get the error `"is_Null_NS" not resolved from current
# namespace (rstan)`
# Restart R session, then:
library(tmbstan)

# Then:
library(sdmTMB)

# Then:
set.seed(42)
pcod_pos <- subset(pcod, year > 2013 & density > 0)
pcod_pos_spde <- make_spde(pcod_pos$X/10, pcod_pos$Y/10, n_knots = 200) # scale UTMs for #' Stan
m <- sdmTMB(pcod_pos,
 log(density) ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
 time = "year", spde = pcod_pos_spde)
m_stan <- tmbstan(m$tmb_obj, chains = 1, iter = 200, cores=1,
  init = "last.par.best", control = list(adapt_delta = 0.80, max_treedepth = 20),
  seed = 123, laplace = T)

pars <- c('b_j', 'ln_tau_O', 'ln_tau_E', 'ln_kappa', 'ln_phi')
m_stan2 <- tmbstan(m$tmb_obj, chains = 1, iter = 200, cores=1,
  init = "last.par.best", control = list(adapt_delta = 0.80, max_treedepth = 20),
  seed = 123, laplace = F, pars = pars)

m_stan

```

