---
title: "Tweedie in TMB"
output: html_notebook
---
Started using tmb.template

```{r set-up}
## Load TMB TRUE
library(TMB)
library(tweedie)

## Make C++ file
# TMB::template("tweedie_tmb.cpp")
## Compile and load the model
compile("src/tweedie_tmb.cpp")
dyn.load(dynlib("src/tweedie_tmb"))
```


# Simulate data

```{r}
N <- 100
x <- runif(N, -2, 2)
a <- 3
b <- 1

power <- 1.5 # must be between 1 and 2 for compound poisson-gamma
phi <- 1 # dispersion must be positive
eta <- a + b * x 
mu <- exp(eta) 
y <- rtweedie(N, power = power, mu = mu, phi = phi) 

# plot simulated data 
plot(x, y)
lines(sort(x), mu[order(x)])

hist(y, breaks=30)
```


# Send data to TMB function to get likelihood profiles for parameters

```{r}
## Data and parameters
data <- list(y = y, x = x)
parameters <- list(a=0, b=0, log_phi = log(1), p = 0 )

## Make a function object
obj <- MakeADFun(data, parameters, DLL="tweedie_tmb")

## Call function minimizer
opt <- nlminb(obj$par, obj$fn, obj$gr)

## Get parameter uncertainties and convergence diagnostics
sdr <- sdreport(obj)
sdr

## Get likelihood profiles for individual parameters:
a_profile <- tmbprofile(obj, "a")
b_profile <- tmbprofile(obj, "b")
confint(a_profile)
confint(b_profile)

plot(a_profile)
plot(b_profile)

```

# For comparision, find maximum likelihood parameter estimates using nlminb

```{r}
# function to generate negative log-likelihood for a parameter value
nll_tweedie <- function(par) {
  eta <- par[1] + par[2] * x
  mu <- exp(eta)
  p <- plogis(par[3]) + 1
  phi <- exp(par[4])
  # sum of negative log likelihoods:
  loglik <- log(dtweedie(y, power = p, mu = mu, phi = phi))
  nll <- -sum(loglik) #[is.finite(loglik)]
  print(nll)
  nll
}

tweedie_ml <- nlminb(start = c(a = 0, b = 0, ipx = 0, log_phi = log(1)), nll_tweedie)
tweedie_ml$par 
```


# Check both methods against values are returned with a glm

```{r}
tweedie_glm <- glm(y ~ x, family = tweedie(var.power = 1.5, link.power = 0))
summary(tweedie_glm)
coef(tweedie_glm)
sdr$par.fixed
tweedie_ml$par 
```



