# Fit spatial temporal models to bottom temperature

```{r setup}
library(tidyverse)
library(sdmTMB)

d_trawl <- readRDS(here::here("analysis/tmb-sensor-explore/sensor-data-processed.rds"))

set.seed(39201114)
```

```{r}
withheld_fe <- sample(d_trawl$fishing_event_id, size = round(nrow(d_trawl)*.2))

d_withheld <- filter(d_trawl, fishing_event_id %in% withheld_fe)

d_fit <- filter(d_trawl, !fishing_event_id %in% withheld_fe)

nrow(d_fit) # 3774
nrow(d_withheld) # 943
unique(d_withheld$year) 
unique(d_fit$year)
length(unique(d_fit$year))

# FIXME: need to work out a bug in production on this new data set
# It's crashing TMB.

#d_fit <- d_trawl
#d_withheld <- d_trawl
```

```{r}
spde <- make_spde(d_fit$X, d_fit$Y, n_knots = 250)
plot_spde(spde)
```

```{r}
m_temp1 <- sdmTMB(d_fit, temperature_c ~ 0 + as.factor(year) + depth_scaled,
  # time_varying =  ~ depth_scaled + depth_scaled2,
  time = "year", spde = spde, family = gaussian(link = "identity"), 
  ar1_fields = FALSE,
  anisotropy = FALSE, 
  include_spatial = TRUE, 
  silent = FALSE)

```


```{r}
m_temp1$model$par
# 2 * plogis(m_temp1$model$par[["ar1_phi"]]) - 1
exp(m_temp1$model$par[["ln_phi"]])
```

```{r}
# FIXME: Error in `$<-.data.frame`(`*tmp*`, "est", value = c(7.12313541783276, :replacement has 4716 rows, data has 4717
predictions <- predict(m_temp1)

attributes(m_temp1)

# find source of error in predict function
object <- m_temp1

 nd <- object$data # this has 3,774 rows of data
 lp <- object$tmb_obj$env$last.par # this has 6583 length(lp)
  r <- object$tmb_obj$report(lp)
    length(r$omega_s) # 386
    length(r$epsilon_st) # this is 6176
    length(r$b_rw_t) # this has 16 time steps
    length(r$eta_i) # this is a vector of 3773
    
    nd$est <- r$eta_i # ERROR OCCURS HERE
    nd$est_fe <- r$eta_fixed_i # ERROR OCCURS HERE

attributes(r)

```

```{r}
predictions$data$residuals <- residuals(m_temp1)
```

```{r}
plot_map <- function(dat, column = "est") {
  ggplot(dat, aes_string("X", "Y", colour = column)) +
    geom_point() +
    facet_wrap(~year) +
    coord_fixed()
}
```

```{r}
plot_map(predictions$data, "est") +
  scale_colour_viridis_c() +
  ggtitle("Prediction (fixed effects + all random effects)")
```


```{r}
plot_map(predictions$data, "est_fe") +
  ggtitle("Prediction (fixed effects only)") +
  scale_colour_viridis_c()

plot_map(predictions$data, "est_re_s") +
  ggtitle("Spatial random effects only") +
  scale_colour_gradient2()

plot_map(predictions$data, "est_re_st") +
  ggtitle("Spatiotemporal random effects only") +
  scale_colour_gradient2()

ggplot(predictions$data, aes(est, temperature_c)) +
  geom_point() +
  facet_wrap(~year) +
  coord_fixed() +
  geom_abline()

ggplot(predictions$data, aes(est, residuals)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year)

ggplot(predictions$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year)

ggplot(predictions$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth()

ggplot(predictions$data, aes(X, Y, colour = residuals)) +
  geom_point() +
  facet_wrap(~year) +
  coord_fixed() +
  scale_color_gradient2()


# Looks a bit curved, let's try with a quadratic

m_temp2 <- sdmTMB(d_fit, temperature_c ~ 0 + as.factor(year) + poly(depth_scaled, 2),
  time = "year", spde = spde, family = gaussian(link = "identity"),
  silent = TRUE)

predictions2 <- predict(m_temp2)
predictions2$data$residuals <- residuals(m_temp2)

ggplot(predictions2$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year)

ggplot(predictions2$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth()

ggplot(predictions2$data, aes(X, Y, colour = residuals)) +
  geom_point() +
  facet_wrap(~year) +
  coord_fixed() +
  scale_color_gradient2()


# Try with a third degree polynomial:
m_temp3 <- sdmTMB(d_fit, 
  temperature_c ~ 0 + as.factor(year) + poly(depth_scaled, 3),
  time = "year", spde = spde, family = gaussian(link = "identity"),
  silent = FALSE)

m_temp3_rw <- sdmTMB(d_fit,
  temperature_c ~ 0 + as.factor(year),
  time_varying =  ~ 0 + poly(depth_scaled, 3),
  include_spatial = FALSE, ar1_fields = TRUE,
  time = "year", spde = spde, family = gaussian(link = "identity"),
  silent = FALSE)


predictions3 <- predict(m_temp3)
predictions3$data$residuals <- residuals(m_temp3)

predictions3_rw <- predict(m_temp3_rw)
predictions3_rw$data$residuals <- residuals(m_temp3_rw)


ggplot(predictions3_rw$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year)

ggplot(predictions3$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth()

ggplot(predictions3$data, aes(X, Y, colour = residuals)) +
  geom_point() +
  facet_wrap(~year) +
  coord_fixed() +
  scale_color_gradient2()

# That's getting pretty straight although it looks a bit heteroscedastic

# Perhaps this would work better with log temperature as the response
# since it basically isn't going to go lower than 0 degree celsius

d_fit$log_temperature_c <- log(d_fit$temperature_c)
m_temp4 <- sdmTMB(d_fit, log_temperature_c ~ 0 + as.factor(year) + poly(depth_scaled, 3),
  time = "year", spde = spde, family = gaussian(link = "identity"),
  silent = TRUE)

predictions4 <- predict(m_temp4)
predictions4$data$residuals <- residuals(m_temp4)

ggplot(predictions4$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year)

ggplot(predictions4$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth()

ggplot(predictions4$data, aes(X, Y, colour = residuals)) +
  geom_point() +
  facet_wrap(~year) +
  coord_fixed() +
  scale_color_gradient2()

# That might've helped a little but not a lot. Let's try with depth and not log depth.

m_temp5 <- sdmTMB(d_fit, temperature_c ~ 0 + as.factor(year) + poly(depth_m, 3),
  time = "year", spde = spde, family = gaussian(link = "identity"),
  silent = TRUE)

predictions5 <- predict(m_temp5)
predictions5$data$residuals <- residuals(m_temp5)

ggplot(predictions5$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year)

ggplot(predictions5$data, aes(depth_scaled, residuals)) +
  geom_point() +
  geom_smooth()

# I don't think that helps with the heteroscedasticity but it made the curvature of the residuals a little bit worse.

ggplot(predictions5$data, aes(est, residuals)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year)

ggplot(predictions5$data, aes(est, residuals)) +
  geom_point() +
  geom_smooth()

aic <- function(m) {
  k <- length(m$model$par)
  nll <- m$model$objective
  2 * k - 2 * (-nll)
}
aic(m_temp1)
aic(m_temp2)
aic(m_temp3)
aic(m_temp4)
aic(m_temp5)

# Conclusion: log depth, 3rd order polynomial with depth

ggplot(predictions3$data, aes(est, temperature_c)) +
  geom_point() +
  facet_wrap(~year) +
  coord_fixed() +
  geom_abline()

# R2
cor(predictions3$data$est, predictions3$data$temperature_c)^2

# Extrapolate:

predictions3_nd <- predict(m_temp3, newdata = sdmTMB::qcs_grid)
saveRDS(predictions3_nd$data, file = "analysis/tmb-sensor-explore/qcs-temp.rds")

ggplot(predictions3$data, aes(X, Y, colour = residuals)) +
  geom_point() +
  facet_wrap(~year) +
  coord_fixed() +
  scale_color_gradient2()

# A short function for plotting our predictions:
plot_map <- function(dat, column = "est") {
  ggplot(dat, aes_string("X", "Y", fill = column)) +
    geom_raster() +
    facet_wrap(~year) +
    coord_fixed()
}

plot_map(predictions3_nd$data, "est") +
  scale_fill_viridis_c(trans = "sqrt", option = "C") +
  ggtitle("Prediction (fixed effects + all random effects)")

plot_map(predictions3_nd$data, "est_fe") +
  ggtitle("Prediction (fixed effects only)") +
  scale_fill_viridis_c(trans = "sqrt")

plot_map(predictions3_nd$data, "est_re_s") +
  ggtitle("Spatial random effects only") +
  scale_fill_gradient2()

plot_map(predictions3_nd$data, "est_re_st") +
  ggtitle("Spatiotemporal random effects only") +
  scale_fill_gradient2()

temp_cog <- get_cog(predictions3_nd)

temp_cog %>% reshape2::dcast(year ~ coord, value.var = "est") %>%
  ggplot(aes(X, Y, colour = year)) + geom_path(arrow = arrow()) +
  scale_color_viridis_c()

temp_cog %>%
  ggplot(aes(year, est, ymin = lwr, ymax = upr)) +
  geom_line() +
  geom_ribbon(alpha = 0.2) +
  facet_wrap(~coord, scales = "free_y")
```